namespace Anarchy.Inputs
{
    internal enum InputTitan : int
    {
        TitanForward,
        TitanBackward,
        TitanLeft,
        TitanRight,
        TitanJump,
        TitanKill,
        TitanWalk,
        TitanPunch,
        TitanSlam,
        TitanGrabFront,
        TitanGrabBack,
        TitanGrabNape,
        TitanSlap,
        TitanBite,
        TitanCoverNape,
        TitanSit,
        TitanStomp,
        TitanKick,
        TitanSlapFace,
        TitanSlapNeck,
        TitanLeftSlap,
        TitanRightSlap,
        TitanSlapLow,
        TitanLeftSlapLow,
        TitanRightSlapLow,
        TitanLeftBite,
        TitanRightBite
    }
}