namespace ExitGames.Client.Photon.RpcProtocols.GpBinaryV18
{
    public enum GpTypeV18 : byte
    {
        Unknown,
        Boolean = 2,
        Byte,
        Short,
        Float,
        Double,
        String,
        Null,
        CompressedInt,
        CompressedLong,
        Int1,
        Int1_,
        Int2,
        Int2_,
        L1,
        L1_,
        L2,
        L2_,
        Custom,
        CustomTypeSlim = 0x80,
        Dictionary = 20,
        Hashtable,
        ObjectArray = 23,
        OperationRequest,
        OperationResponse,
        EventData,
        BooleanFalse,
        BooleanTrue,
        ShortZero,
        IntZero,
        LongZero,
        FloatZero,
        DoubleZero,
        ByteZero,
        Array = 0x40,
        BooleanArray = 66,
        ByteArray,
        ShortArray,
        DoubleArray = 70,
        FloatArray = 69,
        StringArray = 71,
        HashtableArray = 85,
        DictionaryArray = 84,
        CustomTypeArray = 83,
        CompressedIntArray = 73,
        CompressedLongArray,
        CustomData = 255
    }
}
